disabled_rules:
  - todo
  - identifier_name
  - opening_brace
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - implicit_return
  - joined_default_parameter
  - literal_expression_end_indentation
  - overridden_super_call
  - prohibited_super_call
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition
  - nslocalizedstring_key
  - unused_setter_value
  - unused_import
  - optional_enum_case_matching
  - prefer_self_type_over_type_of_self
  - contains_over_range_nil_comparison
  - flatmap_over_map_reduce
  - empty_collection_literal
  - contains_over_first_not_nil
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - reduce_into
custom_rules:
  comment_whitespace:
    name: "Comment Whitespace"
    regex: //\S
    match_kinds: comment
    message: "Comments must begin with a whitespace character"
  spaces_not_tabs:
    name: "Spaces not Tabs"
    regex: ^\t
    message: "Use four spaces, not tabs"
  point_zero:
    name: "Point Zero"
    regex: '(?<!iOS\s)(?<!macOS\s)(?<!\.)\b[\d_]+\.0\b'
    match_kinds:
      - number
      - attribute.builtin
    message: "Don't add a .0 to the end of floating point literals"
type_body_length: 400
function_body_length: 150
line_length:
    warning: 150
    error: 200
    ignores_comments: true
    ignores_urls: true
file_length: 1200
cyclomatic_complexity: 12
