name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Provide a detailed description of the feature you'd like to see added, including the use case and how you envision it working.
      placeholder: |
        Example: "Add dark mode support for better reading experience in low light conditions. This would include dark themes for all UI elements and reading pages."
    validations:
      required: true
