name: SwiftLint

on:
  pull_request:
    paths:
      - ".github/workflows/lint.yml"
      - ".swiftlint.yml"
      - "**/*.swift"

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install SwiftLint
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint lint --reporter github-actions-logging
